name: Build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  build-unix:
    name: on ${{ matrix.name }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux
          os: ubuntu-latest
    steps:
      # Checkout the repository and all submodules
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true         # Fetch submodules
        submodules-depth: 1       # Limit depth for submodule checkout (optional)
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies for Linux
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev
        cp /runner/zelda3.sfc /runner/_work/zelda3/zelda3/zelda3.sfc
    - name: Build
      run: make all
      #run: make -j$(nproc) zelda3
