name: Build

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  build-unix:
    name: on ${{ matrix.name }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Linux
          os: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies for Linux
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev
    - name: Build
      run: make -j$(nproc) zelda3
